language: python
python: '3.6'
install:
- pip install .
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: EDEKA_DIGITAL
  password:
    secure: dwEDlhJUqqHhicZ4OfTKV3cdxP8caVYS2nogwvM99q/8Hiuwn1lbsrCXkMRs6FQw73kww91cobqhsjMRE/uPt5tNGWK9nuTDUR8OlzWJWY/sMneME9CY0rZvseV3A2UF6iJlHtDN3BQBOkNGhnoYS7aqTYWUZpok+vJbWPauiZ4aHKVJupoFNbgvBRgCxgDy7hda+d8xiSCfmeu+jxEgTB+yXQidrUsrC9aecqWafvrtQK4Q7zoicFQdvIkBPbEBzpuZOeHmx/ewwa7vXOhi6KhnQdxf7bsrnqcWur4wxzGgqbgyydBwF12xbgfURIxyT1Ni8xvdhz4i5wxWvm1rpUt4Y7dXLaroensQrLSv0f6j+/Z+crV2WHPN3DBrnUaNKWECB/WhXSpUtbuaUyiw7MtJn39xUeAwQYyL+z0XUAJXd0cluLHipe0qklgspQZx0Tlj7mUYFFGNOcE42vOIsWk4OyqhRkHTRAlNIQYdZJ2SpcgGd3afXsrHW7LEEM05YxIgVibkRK0J16ciIH4ZId049NApw0ts4Dv7zVVgfJoOzBx1w+xX8p8VyCADwvS//BgRViODmwrifwviabw8TT3y8OWauCkDncBB7+U8pGq5MMYXg350pj+mEoSGomA8W3VJwLZ7nofvaaFJNdkL3f6CzgtHzAHIh/MEJfhtG5k=
  on:
    branch: master
